### ISSUE TITLE
Convert remaining locale-types to core.

### ISSUE THREAD

**Issue by elden1337** [elden1337/hass-peaq#111]
### These are the types to be converted:
- [x] (QUERYTYPE_BASICMAX)
- [x] (QUERYTYPE_AVERAGEOFTHREEDAYS)
- [x] (QUERYTYPE_AVERAGEOFTHREEHOURS)
- [x] (QUERYTYPE_AVERAGEOFFIVEDAYS)

- [x] elden1337/peaqev-core#18
- [x] elden1337/peaqev-core#19
- [x] elden1337/peaqev-core#20
- [x] elden1337/peaqev-core#21
- [x] elden1337/peaqev-core#22

### These types can be removed when all conversions are done. They are obsolete then:
* QUERYTYPE_AVERAGEOFTHREEDAYS_MIN
* QUERYTYPE_AVERAGEOFTHREEHOURS_MIN
* QUERYTYPE_AVERAGEOFFIVEDAYS_MIN
* QUERYTYPE_AVERAGEOFTHREEHOURS_MON_FRI_07_19_MIN
* QUERYTYPE_SOLLENTUNA_MIN

### Acceptance criteria per task:

* All locales holding the querytype must have `converted = True` (in corresponding [country/ies](https://github.com/elden1337/peaqev-core/tree/main/Peaqevcore/country))
* LocaleQuery-class (and possibly surrounding helperclasses) must be expanded to accommodate the extra logic on the reamining querytypes [core-repo: querytypes.py](https://github.com/elden1337/peaqev-core/blob/main/Peaqevcore/locale/querytypes.py). See [sqlsensorhelper.py](https://github.com/elden1337/hass-peaq/blob/main/custom_components/peaqev/peaqservice/util/sqlsensorhelper.py)
* At least one test must be written to prove the test in [core-repo: test_localetypes.py](https://github.com/elden1337/peaqev-core/blob/main/Peaqevcore/tests/test_localetypes.py)

_Note, do not comment out or remove data in sqlsensorhelper.py when done. We'll remove that later._
